In [20]:
# dependencies
import pandas as pd

# import all weather csvs
NOAA2013 = "./Data/NOAA_2013.csv"
NOAA2014 = "./Data/NOAA_2014.csv"
NOAA2015 = "./Data/NOAA_2015.csv"
NOAA2016 = "./Data/NOAA_2016.csv"
NOAA2017 = "./Data/NOAA_2017.csv"
NOAA2018 = "./Data/NOAA_2018.csv"
NOAA2019 = "./Data/NOAA_2019.csv"
NOAA2020 = "./Data/NOAA_2020.csv"

# read and store the files in dataframes
Weather2013 = pd.read_csv(NOAA2013)
Weather2014 = pd.read_csv(NOAA2014)
Weather2015 = pd.read_csv(NOAA2015)
Weather2016 = pd.read_csv(NOAA2016)
Weather2017 = pd.read_csv(NOAA2017)
Weather2018 = pd.read_csv(NOAA2018)
Weather2019 = pd.read_csv(NOAA2019)
Weather2020 = pd.read_csv(NOAA2020)

# combine the years of data into one dataframe
WeatherData = pd.concat([Weather2013,Weather2014,Weather2015,Weather2016,Weather2017,
                        Weather2018,Weather2019,Weather2020])

# reset the index to avoid repeats
WeatherData.reset_index(inplace=True,drop=True)

In [21]:
# remove extraneous columns
WeatherData = WeatherData[["STATION","NAME","LATITUDE","LONGITUDE","DATE","DT32","DX90",
                          "EMXP","EMXT","HX01","PRCP","TAVG","TMAX","TMIN","WSF2","WSFG"]]

# rename columns
WeatherData = WeatherData.rename(columns={"STATION":"Station ID","NAME":"Station Name","LATITUDE":"Lat",
                "LONGITUDE":"Long","DATE":"Year"})

In [22]:
WeatherData

,Station ID,Station Name,Lat,Long,Year,DT32,DX90,EMXP,EMXT,HX01,PRCP,TAVG,TMAX,TMIN,WSF2,WSFG
0,USR0000CDIA,"DIABLO GRANDE CALIFORNIA, CA US",37.32920,-121.29390,2013,9.0,49.0,NaN,105.0,NaN,NaN,62.7,72.1,53.2,NaN,NaN
1,US1CALA0036,"PASADENA 2.0 SE, CA US",34.13916,-118.11611,2013,NaN,NaN,0.82,NaN,NaN,5.41,NaN,NaN,NaN,NaN,NaN
2,USR0000CTHO,"THOMES CREEK CALIFORNIA, CA US",39.86440,-122.60970,2013,9.0,90.0,NaN,114.0,NaN,NaN,66.1,76.8,55.4,NaN,NaN
3,US1CABT0002,"OROVILLE 2.7 ENE, CA US",39.51400,-121.51800,2013,NaN,NaN,1.37,NaN,NaN,11.58,NaN,NaN,NaN,NaN,NaN
4,USC00049099,"TWENTYNINE PALMS, CA US",34.12800,-116.03690,2013,13.0,150.0,0.73,117.0,NaN,2.28,70.9,84.4,57.4,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5656,USR0000CLIN,"LINCOLN CALIFORNIA, CA US",38.88250,-121.26830,2020,35.0,128.0,NaN,112.0,NaN,NaN,63.6,78.5,48.6,NaN,NaN
5657,USR0000CJER,"JERSEYDALE CALIFORNIA, CA US",37.54360,-119.83860,2020,44.0,53.0,NaN,102.0,NaN,NaN,59.1,70.2,47.9,NaN,NaN
5658,USC00047339,"REDWOOD CITY, CA US",37.47670,-122.23860,2020,1.0,32.0,0.78,108.0,NaN,6.49,60.7,72.1,49.4,NaN,NaN
5659,USC00040943,"BODIE CALIFORNIA STATE HISTORIC PARK, CA US",38.21190,-119.01420,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5660,USR0000CPRD,"PANOCHE ROAD CALIFORNIA, CA US",36.72690,-120.76580,2020,1.0,60.0,NaN,104.0,NaN,NaN,65.1,72.2,58.1,NaN,NaN

In [23]:
WeatherData = WeatherData.dropna(subset=["DT32","DX90","EMXP","EMXT","HX01","PRCP",
                                         "TAVG","TMAX","TMIN","WSF2","WSFG"],how="all")
WeatherData

,Station ID,Station Name,Lat,Long,Year,DT32,DX90,EMXP,EMXT,HX01,PRCP,TAVG,TMAX,TMIN,WSF2,WSFG
0,USR0000CDIA,"DIABLO GRANDE CALIFORNIA, CA US",37.32920,-121.29390,2013,9.0,49.0,NaN,105.0,NaN,NaN,62.7,72.1,53.2,NaN,NaN
1,US1CALA0036,"PASADENA 2.0 SE, CA US",34.13916,-118.11611,2013,NaN,NaN,0.82,NaN,NaN,5.41,NaN,NaN,NaN,NaN,NaN
2,USR0000CTHO,"THOMES CREEK CALIFORNIA, CA US",39.86440,-122.60970,2013,9.0,90.0,NaN,114.0,NaN,NaN,66.1,76.8,55.4,NaN,NaN
3,US1CABT0002,"OROVILLE 2.7 ENE, CA US",39.51400,-121.51800,2013,NaN,NaN,1.37,NaN,NaN,11.58,NaN,NaN,NaN,NaN,NaN
4,USC00049099,"TWENTYNINE PALMS, CA US",34.12800,-116.03690,2013,13.0,150.0,0.73,117.0,NaN,2.28,70.9,84.4,57.4,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5655,USR0000CHAW,"HAWKEYE CALIFORNIA, CA US",38.78170,-122.91690,2020,0.0,33.0,NaN,107.0,NaN,NaN,61.8,69.9,53.6,NaN,NaN
5656,USR0000CLIN,"LINCOLN CALIFORNIA, CA US",38.88250,-121.26830,2020,35.0,128.0,NaN,112.0,NaN,NaN,63.6,78.5,48.6,NaN,NaN
5657,USR0000CJER,"JERSEYDALE CALIFORNIA, CA US",37.54360,-119.83860,2020,44.0,53.0,NaN,102.0,NaN,NaN,59.1,70.2,47.9,NaN,NaN
5658,USC00047339,"REDWOOD CITY, CA US",37.47670,-122.23860,2020,1.0,32.0,0.78,108.0,NaN,6.49,60.7,72.1,49.4,NaN,NaN
5660,USR0000CPRD,"PANOCHE ROAD CALIFORNIA, CA US",36.72690,-120.76580,2020,1.0,60.0,NaN,104.0,NaN,NaN,65.1,72.2,58.1,NaN,NaN

In [12]:
# pull any rows where all weather data is null
Nones = WeatherData.loc[(WeatherData["DT32"]=!"None")&(WeatherData["DX90"]=="None")&(
    WeatherData["EMXP"]=="None")&(WeatherData["EMXT"]=="None")&(WeatherData["HX01"]=="None")&(
    WeatherData["PRCP"]=="None")&(WeatherData["TAVG"]=="None")&(WeatherData["TMAX"]=="None")&(
    WeatherData["TMIN"]=="None")&(WeatherData["WSF2"]=="None")&(WeatherData["WSFG"]=="None"),:]
Nones = list(Nones.index)

# Exclude = WeatherData.index[(Nones)]
# WeatherData.drop(Exclude,inplace=True)
# excluded = list(Nones.index)
# excluded
# list(Nones.index)

In [13]:
Nones

[17,
 37,
 39,
 65,
 107,
 114,
 123,
 139,
 149,
 167,
 170,
 172,
 176,
 192,
 205,
 212,
 222,
 253,
 282,
 294,
 343,
 350,
 351,
 445,
 500,
 502,
 503,
 519,
 524,
 554,
 584,
 593,
 603,
 608,
 642,
 653,
 702,
 710,
 749,
 827,
 838,
 866,
 877,
 881,
 892,
 948,
 976,
 986,
 1003,
 1059,
 1080,
 1102,
 1126,
 1137,
 1145,
 1159,
 1174,
 1232,
 1233,
 1235,
 1240,
 1284,
 1318,
 1330,
 1344,
 1357,
 1368,
 1400,
 1403,
 1409,
 1419,
 1430,
 1465,
 1491,
 1527,
 1540,
 1584,
 1627,
 1679,
 1705,
 1737,
 1782,
 1789,
 1793,
 1801,
 1808,
 1829,
 1854,
 1943,
 1950,
 1956,
 2001,
 2010,
 2048,
 2063,
 2139,
 2174,
 2210,
 2216,
 2218,
 2248,
 2303,
 2325,
 2326,
 2347,
 2389,
 2409,
 2430,
 2443,
 2518,
 2520,
 2530,
 2537,
 2553,
 2589,
 2591,
 2612,
 2649,
 2664,
 2694,
 2754,
 2766,
 2794,
 2811,
 2856,
 2871,
 2884,
 2921,
 2932,
 2940,
 2992,
 3009,
 3036,
 3053,
 3068,
 3093,
 3099,
 3142,
 3186,
 3203,
 3209,
 3210,
 3221,
 3312,
 3335,
 3358,
 3364,
 3379,
 3392,
 3417,
 3428,
 3433,
 3451,
 3465,
 3481,
 3497,
 3502,
 3504,
 3520,
 3540,
 3559,
 3578,
 3672,
 3702,
 3735,
 3786,
 3803,
 3805,
 3809,
 3832,
 3842,
 3863,
 3911,
 3950,
 3956,
 3997,
 4046,
 4083,
 4089,
 4090,
 4133,
 4143,
 4166,
 4184,
 4189,
 4219,
 4222,
 4229,
 4252,
 4256,
 4276,
 4316,
 4328,
 4337,
 4371,
 4376,
 4409,
 4451,
 4466,
 4517,
 4520,
 4530,
 4541,
 4557,
 4579,
 4632,
 4656,
 4670,
 4770,
 4823,
 4837,
 4853,
 4873,
 4902,
 4912,
 4984,
 4998,
 4999,
 5020,
 5031,
 5035,
 5053,
 5100,
 5162,
 5202,
 5208,
 5215,
 5226,
 5236,
 5248,
 5349,
 5351,
 5377,
 5431,
 5602,
 5615,
 5624,
 5659]

In [ ]:
DataList = list(WeatherData.index)
included = []
for index in DataList:
    if index not in excluded:
        included.append(index)
WeatherData = WeatherData.iloc[included]

In [ ]:
WeatherData

In [ ]:
# do county lookup, separate dataframes by weather, drop NaNs, then aggregate by county